### PR TITLE
Add type annotations to Database, Message and Signal

### PR DESCRIPTION
**Pull request by zariiii9003**
Add some type annotations to improve code completion in IDEs

### CODE REVIEW

**Comment by juleq** [comment]
@zariiii9003 thanks. What tooling do you use for type checking?

@andlaus Since Python 3 is already required, I would see this as beneficial and I have no concerns. Agreed?

**Comment by zariiii9003** [comment]
Usually i use mypy for my projects. But here i did not use any type checker. I only annotated some of the user facing code manually to help with code completion in PyCharm.

While i would like to see cantools being fully type checked that would be a huge PR and nobody would review it.

**Comment by andlaus** [comment]
> @andlaus Since Python 3 is already required, I would see this as beneficial and I have no concerns. Agreed?

agreed: No concerns from my side either. Maybe having a test would be good, but I cannot see how to easily do one.

**Comment by juleq** [comment]
@zariiii9003 If you can confirm a successful check of mypi against your annotations I will merge. If you happen to find a way to call mypi in our CI and add some simple tests, that would yield bonus points :).

**Comment by juleq** [comment]
@zariiii9003 good job. Time to merge. You can enjoy with the next release :).

**Comment by juleq** [comment]
@zariiii9003 is there a way to check the linter output? Could not find it (on mobile ATM).

**Comment by zariiii9003** [comment]
@juleq 
[The CI Output is here](https://github.com/cantools/cantools/runs/4780831548?check_suite_focus=true#step:5:11).
```
run mypy --python-version 3.6 cantools
Success: no issues found in 47 source files
```

You can run `mypy cantools` on your local repo.

**Pull request merged**
