### PR TITLE
Add Support for Dumping Database as SYM File

### PR DESCRIPTION
**Pull request by samc1213**
* Logic to convert cantools database to sym file
* Basic unit tests written - may be limitations converting from specific formats to SYM, but general functionality is implemented

### CODE REVIEW

**Review by andlaus — APPROVED** [review]
looks good. @samc1213: To me it seems like this does not affect the "core"of cantools, but only the SYM file format support, right?  If so, I recommend merging this @juleq...

**Comment by andlaus** [comment]
>  If so, I recommend merging this ...

... after the mypy issues have been fixed (obviously)

**Comment by samc1213** [comment]
@andlaus there are no core changes, only affects SYM files in an additive manner. I want to add more tests and fix mypy before merging. Thanks for your prompt review

**Comment by samc1213** [comment]
@andlaus testing with the Jopp 6.0 file helped find some bugs. I think this is ready for merge

**Pull request merged**
