### PR TITLE
Changed relative links to absolute links

### PR DESCRIPTION
**Pull request by erzoe**
trying to fix [this issue](https://github.com/cantools/cantools/issues/487#issuecomment-137139501)

### CODE REVIEW

**Comment by juleq** [comment]
Thanks. Do you have an easy way to try or should I just do a patch release?

**Comment by zariiii9003** [comment]
There's another one on line 146

**Comment by erzoe** [comment]
> There's another one on line 146

How embarrassing. Yes you are right, thank you. I have added another commit.

**Comment by erzoe** [comment]
> Thanks. Do you have an easy way to try or should I just do a patch release?

Well, I had verified that the images are visible in the README on my fork. But that is not a good test, because they were visible there before the changes, too.

Now I have checked with grep that I have not missed any links again and it looks good:

```bash
$ grep docs/ README.rst 
.. image:: https://github.com/cantools/cantools/raw/master/docs/plot-1.png
.. image:: https://github.com/cantools/cantools/raw/master/docs/plot-2-subplots.png
.. image:: https://github.com/cantools/cantools/raw/master/docs/plot-2-axes.png
.. image:: https://github.com/cantools/cantools/raw/master/docs/plot-seaborn.png
.. image:: https://github.com/cantools/cantools/raw/master/docs/monitor.png
```

**Comment by erzoe** [comment]
By the way, what would be the right way to deal with links in merge requests? Because if I used absolute links like this I would not be able to test them before the merge. Using absolute links to my fork would not seem right because if I would update an image on my fork during development they would show unmerged development in the official documentation. But using relative links has proven to cause problems, too.

**Comment by andlaus** [comment]
> By the way, what would be the right way to deal with links in merge requests?

IMO, just use the URIs where you expect them to go. If it takes a few tries to get it right, so be it... (I'm quite surprised/shocked that relative links don't work here, though.)

**Comment by andlaus** [comment]
@juleq: I suppose it is worth to give this a shot and merge...

**Pull request merged**
