### PR TITLE
Remove Decimal from docs

### PR DESCRIPTION
**Pull request by zariiii9003**

### CODE REVIEW

**Comment by andlaus** [comment]
good catch. As far as I can see, the documentation needs some love in general...

**Comment by andlaus** [comment]
@zariiii9003, @juleq: are you aware of any issues that preventing a 39.0.0 release? if no, I'd like to get over this hump soonish...

**Comment by zariiii9003** [comment]
@andlaus I didn't really have much time to test it. But there seems to be a regression. Maybe you can tell the reason without access to the arxml file 😄 

```text
Traceback (most recent call last):
  File "D:\PythonProjekte\cantools\cantools\database\__init__.py", line 363, in load_string
    return load_can_database('arxml')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\__init__.py", line 348, in load_can_database
    db.add_arxml_string(string)
  File "D:\PythonProjekte\cantools\cantools\database\can\database.py", line 262, in add_arxml_string
    database = arxml.load_string(string, self._strict, sort_signals=self._sort_signals)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\__init__.py", line 73, in load_string
    return SystemLoader(root, strict, sort_signals).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 152, in load
    messages = self._load_messages(root_packages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 652, in _load_messages
    messages.extend(self._load_package_messages(package))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 713, in _load_package_messages
    messages.append(self._load_message(bus_name,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 784, in _load_message
    self._load_pdu(pdu, name, 1)
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 1100, in _load_pdu
    signals = self._load_pdu_signals(pdu)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 1337, in _load_pdu_signals
    signal = self._load_signal(i_signal_to_i_pdu_mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 1492, in _load_signal
    self._load_system_signal(system_signal, is_float)
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 1913, in _load_system_signal
    comments = self._load_comments(system_signal)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjekte\cantools\cantools\database\can\formats\arxml\system_loader.py", line 1374, in _load_comments
    tmp = [ x.strip() for x in l_2.text.split('\n') ]
                               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by andlaus** [comment]
speculation: does your file contain an `<L-2>` tag that is immediately closed a la `<L-2 />`? The `ElementTree` node for one of the comments of a system signal does not seem to exhibit a `.text` attribute and as far as I'm aware, this only happens if tags are immediately closed. while at this, can you validate your file against the AUTOSAR XSD? (you can almost certainly download the XSD from their website, but they make it extraordinarily hard to find it for some reason and I can't find anymore it after they changed their site a while back.)

**Comment by andlaus** [comment]
>  A simple check solves the problem if you agree:

I agree, but a comment without any content does not make sense? That said, it's AUTOSAR...

**Comment by andlaus** [comment]
finally! I found the XSD: https://www.autosar.org/fileadmin/standards/R21-11/FO/AUTOSAR_MMOD_XMLSchema.zip

**Comment by zariiii9003** [comment]
I don't know how to validate it. But it does indeed contain two of these:
```xml
          <DESC>
            <L-2 L="FOR-ALL" />
          </DESC>
```
The schema version is 4.3.0

**Comment by zariiii9003** [comment]
xmllint seems happy with the file. Would you prefer to skip or to add an emtpy string as comment?

**Comment by andlaus** [comment]
> xmllint seems happy with the file. 

with autosar there never is any worry about the lack of surprises... ;)

> Would you prefer to skip or to add an emtpy string as comment?

I think it is better to skip it: An empty comment for a language is functionally the same as no comment for that language...

**Pull request merged**
