### PR TITLE
ARXML: improve reference handling

### PR DESCRIPTION
**Pull request by andlaus**
This improves handling of references in ARXML insofar that arbitrary objects may now be referenced (instead of just elements of packages) and that the somewhat reasonable use cases for relative references are now supported.

Andreas Lauser &lt;<andreas.lauser@daimler.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by juleq** [comment]
I cannot do an in-depth review on this. But since new features are welcome, just ask for a merge when done. Done?

**Comment by andlaus** [comment]
> Done?

regarding the ARXML functionality, yes: as far as I can see it works and it should not regress anything. You *might* have a few more general some objections, though. (e.g. I tend to mess up the coding style quite often...)

**Comment by juleq** [comment]
I see :). Most notably, there are a few places where you have violated Erics rule concerning the nowline before and after compund statements (if, for). I like that rule ^^.

**Comment by andlaus** [comment]
> I see :). Most notably, there are a few places where you have violated Erics rule concerning the newline before and after compund statements (if, for). I like that rule ^^.

okay, I hope to have fixed this by now. (note: given that this was rather trivial, it was quite a bit more work than I anticipated...)

**Pull request merged**
