### PR TITLE
Fix parsing of referenced data in CDDs

### PR DESCRIPTION
**Pull request by 1atabey1**
Some data objects are not directly part of the variant specific DID XML elements but are instead referencing to another location, this pr helps with that.
All diagnostics unit tests are still passing and a new test for this functionality has been added.

### CODE REVIEW

**Comment by 1atabey1** [comment]
This addresses issue https://github.com/cantools/cantools/issues/434

**Review by andlaus — COMMENTED** [review]
The PR looks fine to me. That said, I've got zero experience with non-UDS diagnostics.

**Comment by juleq** [comment]
Could you check why the cdd diff is so massive. Github will not render...

**Comment by 1atabey1** [comment]
> Could you check why the cdd diff is so massive. Github will not render...
> 
> And linter is unhappy. Maybe have a look there, too.

Just pushed a change that should make the linter happy.

The cdd was generated using Vector's CANdela Studio, I already deleted all diagnostic instances that I could.. unfortunately vector is not really known for their easy readable and lightweight formats (: 
I can try and modify one of the existing cdds but that would probably also cause a huge diff (and a lot of unit tests that I would have to fix) so not sure if that's worth it

**Comment by juleq** [comment]
Thats fine. Just wanted to make sure the diff size is not due to some formatting issue. Merging, thank you.

**Pull request merged**
