### PR TITLE
Add group_comment_signals flag to DBC output

### PR DESCRIPTION
**Pull request by mon**
Some more DBC output knobs to twiddle :)

Currently, comments are serialised as
- Node comment 1
- Node 1 message comment 1
- Node 1 message comment n
- Node comment 2
- Node 2 message comment 1

This changes things to be
- Node comment 1
- Node comment 2
- Node 1 message comment 1
- Node 1 message comment n
- Node 2 message comment 1

### CODE REVIEW

**Comment by andlaus** [comment]
what's the point of this? (the result seems to be quite equivalent to me...)

**Comment by mon** [comment]
I'm making a dbc formatter - cantools already has a wealth of ways to adjust how DBC files are serialised (signal order, attribute order, enum order, long name cutoffs), this just adds one more thing.

**Comment by andlaus** [comment]
IMO we should strive to remove knobs if they are of limited use, not add new ones. In this particular case, the loaded database should even be identical, so I really don't see the point...

**Comment by mon** [comment]
Alright, well, just to be clear: Are the previous knobs going to (eventually) be removed, or is it just a case of not adding new ones?

**Comment by andlaus** [comment]
In the medium term, nothing existing will be removed, and even in the long term I'll only advocate to go after stuff which is has only esthetic effects on the produced output files (which, as far as I can see, is not much).

The reason why I'd like to limit options is that I'd like to keep cantools usable for the 98.5% of people who don't care about such things and forward the remaining people to tools like yours. (We can't possibly maintain this for each and every file format which we support.)

**Comment by mon** [comment]
Ok! It's very understandable as a maintenance burden. I'll consider ways to decouple cantools output from my formatting steps.

**Comment by andlaus** [comment]
if you publish your DBC-linter, we can mention it in the cantools README if you want...

**Comment by mon** [comment]
Oh, that might be nice! It's very opinionated so far (and potentially even incompatible with some tools due to converting to Unix line endings), so I may have to consider whether to do a full release, or a "this is what is possible" gist that others can extend.

**Comment by mon** [comment]
Closing for now, and hopefully I can revisit this later by publishing my formatter. Thanks for your patience explaining your reasoning!

**Comment by andlaus** [comment]
thanks for your patience and understanding. don't let yourself be deterred to contribute in the future by this :)

**Comment by mon** [comment]
Good news! I've been able to publish my formatter. Hopefully it explains why I've been asking for all these features :)
https://github.com/mon/dbc_format

**Pull request closed without merging**
