### PR TITLE
Make scale and offset attribute of Decimal mandatory

### PR DESCRIPTION
**Pull request by zariiii9003**
Related to the discussion in #515

### CODE REVIEW

**Review by andlaus — APPROVED** [review]
seems good. This probably means that numerical physical values are now always `float`?

**Comment by zariiii9003** [comment]
> This probably means that numerical physical values are now always `float`?

How so? I hope i did not change any behavior.

**Comment by andlaus** [comment]
> How so? I hope i did not change any behavior.

Not sure, but possibly the internal value could now always be transformed via the scaling equation
```
y = x*s + o
```

with `s` and `o` being `float`.

to be clear: I am all for this, let's get it merged.

**Comment by andlaus** [comment]
#555 should also fix this? (by removing the Decimal objects)

**Pull request merged**
